language: php
php:
  - hhvm
addons:
  code_climate:
    repo_token: 292bd2078185242e92ef71b7a8e2ef71a0fff156a34ed492d292424b7b3086fd

script: phpunit --coverage-clover clover.xml

after_script:
  - vendor/bin/test-reporter
